improved filter design
wingkwong/react-quiz-component pull request #147
Opened 2023-10-23 18:29 UTC by VishakhaSainani

fix : #144 

Screenshots: 
![React Quiz Component Demo - Google Chrome 23-10-2023 23_57_26](https://github.com/wingkwong/react-quiz-component/assets/113436770/a8e90834-4202-4f4e-9fdc-835298fd5330)
![React Quiz Component Demo - Google Chrome 23-10-2023 23_57_42](https://github.com/wingkwong/react-quiz-component/assets/113436770/0432c70b-c97b-4161-92e6-a725e9aedc66)

I used div , li and ul were giving lint errors. Check this out.

2023-10-23 18:30 UTC, VishakhaSainani commented
@wingkwong Please review it.

2023-10-24 04:08 UTC, wingkwong requested changes
1. the filter is not working at all...
2. the new filter is a bit large. You may refer to [ant design select](https://ant.design/components/select) - the first one in basic usage. It's close to my expectation.
3. wrap the style by `.react-quiz-container`. i.e. `.react-quiz-container .quiz-result-filter`
4. need a better name for `custom-select`

2023-10-25 09:09 UTC, VishakhaSainani commented
@wingkwong Requested changes updated please check.

2023-10-25 16:43 UTC, wingkwong commented
> Can you please elaborate this one, of what item exactly the height needs to be changed. The select button or the cursor arrow or the dropdown menu.

The overall height. Now it's 42px. Change to 32px. The text and arrow down icon can be a bit smaller.

![image](https://github.com/wingkwong/react-quiz-component/assets/35857179/ada9558c-bb2b-417c-b440-21a3c0346503)

2023-10-25 20:56 UTC, VishakhaSainani commented
@wingkwong Check it out. Thankyou.

2023-10-26 11:08 UTC, wingkwong reviewed
- open a select option list, unfocus should close the list. 
- the font size of selected option and that of options in the list are not aligned
- the gap between the select and the list should be reduced a bit
![image](https://github.com/wingkwong/react-quiz-component/assets/35857179/6e4d8e98-7228-4a6a-a643-60a0cdf256ff)

2023-10-26 11:08 UTC, wingkwong commented on src/lib/styles.css
> +  margin-top: -18px;
don't use negative value. It's a bad practice.

2023-10-26 11:08 UTC, wingkwong commented on src/lib/styles.css
> +    margin-bottom: -5px;
same as above

2023-10-26 11:08 UTC, wingkwong commented on src/lib/styles.css
> +    height: 12.45px;
shouldn't set decimal.

2023-10-26 11:08 UTC, wingkwong commented on src/lib/styles.css
> +    font-weight:lighter;
make sure there is a space after `:` (apply to all)

2023-10-26 11:08 UTC, wingkwong commented on src/lib/styles.css
> +  .dropdown-options .dropdown-options-item:focus{
make sure there is a space after `{` (apply to all)

2023-10-27 06:58 UTC, VishakhaSainani commented
@wingkwong I hope it's good enough now, check it out. Thankyou

2023-10-27 07:13 UTC, wingkwong approved these changes

2023-10-27 07:14 UTC, merged